[tool.poetry]
name = "nowplaying-impression"
version = "0.1.0"
description = ""
authors = ["Chris Barry <2490974+ChrisW-B@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
pylast = "^4.4.0"
Pillow = "^8.4.0"
hitherdither = {git = "https://www.github.com/hbldh/hitherdither"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
